CREATE TABLE IF NOT EXISTS brands (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  logo_top TEXT,
  overlay_path TEXT,
  logo_end TEXT,
  caption_style TEXT DEFAULT 'bold',
  caption_text_color TEXT DEFAULT '#ffffff',
  caption_bg_color TEXT DEFAULT '#000000',
  caption_outline_color TEXT DEFAULT '#000000',
  caption_outline_width REAL DEFAULT 0,
  caption_outline_mode TEXT DEFAULT 'center',
  caption_font_size INTEGER DEFAULT 46,
  caption_font_weight TEXT DEFAULT '700',
  caption_font_style TEXT DEFAULT 'normal',
  caption_text_case TEXT DEFAULT 'none',
  caption_letter_spacing REAL DEFAULT 0,
  caption_active_padding INTEGER DEFAULT 8,
  caption_active_radius INTEGER DEFAULT 6,
  caption_position TEXT DEFAULT '50,78',
  font_family TEXT DEFAULT 'Plus Jakarta Sans',
  font_path TEXT,
  primary_color TEXT DEFAULT '#ef4444',
  logo_position TEXT DEFAULT 'top-right',
  logo_top_scale REAL DEFAULT 1,
  logo_end_scale REAL DEFAULT 1,
  logo_top_in_animation TEXT DEFAULT 'none',
  logo_top_in_duration REAL DEFAULT 0.6,
  logo_top_out_animation TEXT DEFAULT 'none',
  logo_top_out_duration REAL DEFAULT 0.6,
  logo_end_in_animation TEXT DEFAULT 'none',
  logo_end_in_duration REAL DEFAULT 0.6,
  logo_end_out_animation TEXT DEFAULT 'none',
  logo_end_out_duration REAL DEFAULT 0.6,
  thumbnail_image TEXT,
  thumbnail_font_family TEXT DEFAULT 'Bungee',
  thumbnail_bg_color TEXT DEFAULT '#001dff',
  thumbnail_text_color TEXT DEFAULT '#ffffff',
  thumbnail_font_size INTEGER DEFAULT 46,
  thumbnail_font_weight TEXT DEFAULT '700',
  thumbnail_font_style TEXT DEFAULT 'normal',
  thumbnail_text_case TEXT DEFAULT 'none',
  thumbnail_outline_color TEXT DEFAULT '#000000',
  thumbnail_outline_width REAL DEFAULT 0,
  thumbnail_letter_spacing INTEGER DEFAULT 0,
  thumbnail_position TEXT DEFAULT '8,28',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  topic TEXT NOT NULL,
  narration TEXT,
  thumbnail_image TEXT,
  thumbnail_title TEXT,
  post_caption TEXT,
  hashtags TEXT DEFAULT '[]',
  brand_id INTEGER,
  voice_style TEXT,
  voice_path TEXT,
  total_duration REAL DEFAULT 0,
  status TEXT DEFAULT 'draft',
  output_path TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS assets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('video', 'image', 'audio')),
  source_type TEXT NOT NULL CHECK (source_type IN ('upload', 'url')),
  source_path TEXT,
  url TEXT,
  trim_start REAL DEFAULT 0,
  trim_end REAL,
  custom_duration REAL,
  calculated_duration REAL DEFAULT 0,
  order_index INTEGER DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS render_jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  status TEXT DEFAULT 'pending',
  progress INTEGER DEFAULT 0,
  error_message TEXT,
  started_at TEXT,
  finished_at TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);
